name = "job-posting-red-flags-detector"
main = "src/index.ts"
compatibility_date = "2024-11-09"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "def92e00ce8348cd832951f3f57784a0"


# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
